import { ReactNode } from "react";

import { MenuItem, TopLevelCategory } from "@/app/model/type/menu";
import { AppContextProvider } from "@/app/providers/context/appContext";
import { Footer } from "@/widjets/Footer/Footer";
import { Header } from "@/widjets/Header/Header";
import { Sidebar } from "@/widjets/Sidebar/Sidebar";
import { Open_Sans } from "next/font/google";

import "./globals.css";

import s from "./layout.module.scss"; // импорт типов

const inter = Open_Sans({ subsets: ["latin"] });

// Метаданные страницы
export const metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

// Получаем данные через серверные функции
export default function RootLayout({
  children,
  firstCategory,
  menu,
}: {
  children: ReactNode;
  firstCategory: TopLevelCategory; // Категория
  menu: MenuItem[]; // Данные меню
}) {
  return (
    <html lang={"ru"}>
      <body className={inter.className}>
        <div className={s.gridWrapper}>
          <Header className={s.header} />
          <Sidebar className={s.sidebar} />
          <div className={s.body}>
            {/* Передаем динамически значения в провайдер */}
            <AppContextProvider
              firstCategory={firstCategory}
              menu={menu as any}
            >
              {children}
            </AppContextProvider>
          </div>
          <Footer className={s.footer} />
        </div>
      </body>
    </html>
  );
}
